# Generated by Django 2.2.7 on 2019-11-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Costume',
            fields=[
                ('cs_id', models.AutoField(primary_key=True, serialize=False, verbose_name='服装id，自增')),
                ('cs_name', models.CharField(max_length=32, verbose_name='服饰名称')),
                ('gender', models.CharField(default='1', max_length=1, verbose_name='性别')),
                ('describe', models.CharField(max_length=512, null=True, verbose_name='描述')),
                ('material', models.CharField(max_length=16, null=True, verbose_name='材质')),
                ('texture', models.CharField(max_length=32, null=True, verbose_name='纹理')),
                ('dynasty', models.CharField(max_length=16, null=True, verbose_name='朝代')),
                ('cs_sort', models.CharField(max_length=32, verbose_name='服装类别')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False, verbose_name='图片资源id，自增')),
                ('img_name', models.CharField(max_length=32, verbose_name='图片资源名称')),
                ('describe', models.CharField(max_length=256, verbose_name='资源描述')),
                ('costume_name', models.CharField(max_length=32, verbose_name='所属服装')),
                ('url_img', models.ImageField(max_length=128, upload_to='photos', verbose_name='图片文件')),
            ],
        ),
        migrations.CreateModel(
            name='MP3',
            fields=[
                ('mp3_id', models.AutoField(primary_key=True, serialize=False, verbose_name='音频资源id，自增')),
                ('mp3_name', models.CharField(max_length=32, verbose_name='音频资源名称')),
                ('describe', models.CharField(max_length=256, verbose_name='资源描述')),
                ('costume_name', models.CharField(max_length=32, verbose_name='所属服装')),
                ('url_mp3', models.FileField(max_length=128, upload_to='', verbose_name='音频文件')),
            ],
        ),
        migrations.CreateModel(
            name='MP4',
            fields=[
                ('mp4_id', models.AutoField(primary_key=True, serialize=False, verbose_name='视频资源id，自增')),
                ('mp4_name', models.CharField(max_length=32, verbose_name='音频资源名称')),
                ('describe', models.CharField(max_length=256, verbose_name='资源描述')),
                ('costume_name', models.CharField(max_length=32, verbose_name='所属服装')),
                ('url_mP4', models.FileField(max_length=128, upload_to='', verbose_name='视频文件')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户_id, 自增')),
                ('user_name', models.CharField(max_length=16, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码+MD5加密')),
                ('authority', models.CharField(default='', max_length=20, verbose_name='权限')),
            ],
        ),
        migrations.CreateModel(
            name='UserStr',
            fields=[
                ('userStr_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='主键')),
                ('user_name', models.CharField(max_length=16, null=True, unique=True, verbose_name='用户名称')),
                ('str', models.CharField(max_length=10, null=True, verbose_name='加密字符串')),
            ],
        ),
        migrations.CreateModel(
            name='VR',
            fields=[
                ('vr_id', models.AutoField(primary_key=True, serialize=False, verbose_name='VR资源id，自增')),
                ('vr_name', models.CharField(max_length=32, verbose_name='音频资源名称')),
                ('describe', models.CharField(max_length=256, verbose_name='资源描述')),
                ('costume_name', models.CharField(max_length=32, verbose_name='所属服装')),
                ('url_vr', models.FileField(max_length=128, upload_to='', verbose_name='vr文件')),
            ],
        ),
    ]
