# Generated by Django 2.2.7 on 2019-11-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Museum01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url_img',
            field=models.CharField(default='/static/img/clothes.jpg', max_length=128, verbose_name='图片文件路径'),
        ),
        migrations.AlterField(
            model_name='mp3',
            name='url_mp3',
            field=models.CharField(max_length=128, verbose_name='音频文件路径'),
        ),
        migrations.AlterField(
            model_name='mp4',
            name='url_mP4',
            field=models.CharField(max_length=128, verbose_name='视频文件路径'),
        ),
        migrations.AlterField(
            model_name='vr',
            name='url_vr',
            field=models.CharField(max_length=128, verbose_name='vr文件路径'),
        ),
    ]
