# Generated by Django 2.2.7 on 2019-11-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Museum01', '0002_auto_20191121_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='identity',
            field=models.CharField(default='people', max_length=32, verbose_name='身份'),
        ),
    ]
