# Generated by Django 2.2.7 on 2019-11-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Museum01', '0003_user_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='identity',
            field=models.CharField(default='root', max_length=32, verbose_name='身份'),
        ),
    ]
