# Generated by Django 2.2.7 on 2019-11-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Museum01', '0006_user_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstr',
            name='userStr_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='主键'),
        ),
    ]
