# Generated by Django 2.2.7 on 2019-12-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Museum01', '0007_auto_20191130_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='costume',
            name='nation',
            field=models.CharField(max_length=16, null=True, verbose_name='民族'),
        ),
    ]
