# Generated by Django 2.2.7 on 2019-12-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Museum01', '0008_costume_nation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(default='root', max_length=11, unique=True, verbose_name='电话'),
        ),
    ]
