# Generated by Django 2.2.7 on 2019-12-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Museum01', '0009_auto_20191211_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='authority',
            field=models.CharField(default='root', max_length=20, verbose_name='权限'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(default='', max_length=11, unique=True, verbose_name='电话'),
        ),
    ]
