# Generated by Django 2.1.4 on 2020-01-02 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Museum01', '0010_auto_20191211_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costume',
            name='material',
            field=models.CharField(max_length=256, null=True, verbose_name='材质'),
        ),
        migrations.AlterField(
            model_name='costume',
            name='texture',
            field=models.CharField(max_length=256, null=True, verbose_name='纹理'),
        ),
    ]
