# Generated by Django 2.1.4 on 2020-01-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Museum01', '0011_auto_20200102_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='costume',
            name='story',
            field=models.CharField(max_length=1024, null=True, verbose_name='传说故事'),
        ),
    ]
