# Generated by Django 2.1.4 on 2020-05-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Museum01', '0013_user_head_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('md_id', models.AutoField(primary_key=True, serialize=False, verbose_name='模型资源id，自增')),
                ('md_name', models.CharField(max_length=32, verbose_name='模型资源名称')),
                ('url_img', models.CharField(default='/static/img/clothes.jpg', max_length=128, verbose_name='图片文件路径')),
                ('describe', models.CharField(max_length=256, verbose_name='资源描述')),
                ('costume_name', models.CharField(max_length=32, verbose_name='所属服装')),
                ('url_md', models.CharField(max_length=128, verbose_name='模型文件路径')),
            ],
        ),
        migrations.DeleteModel(
            name='VR',
        ),
    ]
