# Generated by Django 2.1.4 on 2020-05-24 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Museum01', '0014_auto_20200524_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='costume_name',
        ),
    ]
